# Generated by Django 3.1.3 on 2021-06-17 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210617_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
