# Generated by Django 3.1.3 on 2021-07-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20210714_1913'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
