# Generated by Django 3.1.3 on 2021-07-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Desc',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
