# Generated by Django 3.1.3 on 2021-07-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_profile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Desc',
            field=models.CharField(blank=True, default=' Write Something About You.', max_length=250),
        ),
    ]
