# Generated by Django 3.1.3 on 2021-07-15 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20210715_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Desc',
            new_name='desc',
        ),
    ]
