# Generated by Django 3.1.3 on 2021-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20210715_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(blank=True, default='Write Something About You', max_length=250, null=True),
        ),
    ]
