# Generated by Django 3.1.3 on 2021-07-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20210715_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(blank=True, help_text='bio', max_length=250, null=True),
        ),
    ]
