# Generated by Django 3.1.3 on 2021-07-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20210715_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pic/default.png', null=True, upload_to='profile_pic'),
        ),
    ]
