# Generated by Django 3.1.3 on 2021-07-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20210716_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pic'),
        ),
    ]
